# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run.
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: zip
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: profile.zip
          exclusions: '*.git* /*node_modules/* .editorconfig *.md'
          # Base path for archive files
          path: UK Dataset/

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "profile.zip"
          target: "/var/www/html/vatsys/"
